# Generated by Django 5.2.7 on 2025-10-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_slug_and_body_to_content'),
        ('content', '0002_article_title'),
    ]

    operations = [
    ]
