# Generated by Django 5.2.7 on 2025-11-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_merge_20251016_0430"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.RemoveField(
            model_name="article",
            name="owner",
        ),
        migrations.DeleteModel(
            name="ArticleCategory",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
